# Generated by Django 6.0.3 on 2026-05-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
